### PR TITLE
Update en.json

### PR DESCRIPTION
**Pull request by daniel-bray**
Fix: minor typo and change gb_short names to be more in line with English server lingo

### CODE REVIEW

**Comment by Heziode** [comment]
Hi @daniel-bray,

This PR should be on dev branch of FOE-Tools and not your branch dev, isn't it ?

**Comment by daniel-bray** [comment]
Yes, you are correct. Seems I didn’t do this correctly.

**Comment by Heziode** [comment]
Indeed, you should close this PR, and re-open a new from your branch `daniel-bray-patch-1` to `FOE-Tools/FOE-Tools.github.io:dev` :wink:

**Comment by daniel-bray** [comment]
Will do. Thank you for pointing out my error. 😁

**Pull request closed without merging**
